import type { StylesheetJson } from 'cytoscape'

export const knowledgeGraphStyles = [
  {
    selector: 'node',
    style: {
      width: 60,
      height: 60,
      shape: 'ellipse',
      label: 'data(label)',
      'text-wrap': 'wrap',
      'text-max-width': 50,
      'text-overflow-wrap': 'anywhere',
      'text-halign': 'center',
      'text-valign': 'center',
      'text-justification': 'center',
      color: 'data(textColor)',
      'font-size': 14,
      'min-zoomed-font-size': 8,
      'font-weight': 700,
      'background-color': 'data(baseColor)',
      'border-width': 1,
      'border-color': 'data(borderColor)',
      'overlay-opacity': 0,
      'transition-property':
        'background-color border-color shadow-blur shadow-opacity width height font-size text-opacity',
      'transition-duration': 160,
      'transition-timing-function': 'ease-in-out',
      'shadow-blur': 8,
      'shadow-color': 'data(shadowColor)',
      'shadow-opacity': 0.16,
      'shadow-offset-x': 0,
      'shadow-offset-y': 0,
    },
  },
  {
    selector: 'edge',
    style: {
      width: 1.8,
      label: 'data(label)',
      color: '#6d816f',
      'font-size': 8,
      'line-color': '#7CBFA9',
      'target-arrow-color': '#7CBFA9',
      'target-arrow-shape': 'triangle',
      'curve-style': 'bezier',
      opacity: 0.72,
      'arrow-scale': 0.9,
      'text-rotation': 'autorotate',
      'text-background-opacity': 1,
      'text-background-color': '#ffffffd9',
      'text-background-padding': 2,
      'min-zoomed-font-size': 8,
      'transition-property': 'width opacity line-color target-arrow-color text-opacity',
      'transition-duration': 160,
      'transition-timing-function': 'ease-in-out',
    },
  },
  {
    selector: 'edge.bridge-edge',
    style: {
      opacity: 0.95,
      width: 2.8,
      label: 'data(label)',
      color: '#00BC7D',
      'font-size': 8,
      'font-weight': 700,
      'line-color': '#00BC7D',
      'target-arrow-color': '#00BC7D',
      'target-arrow-shape': 'triangle',
      'curve-style': 'bezier',
      'underlay-color': '#7ae7c7',
      'underlay-opacity': 0.3,
      'underlay-padding': 5,
      'text-background-color': '#ecfffb',
      'text-background-opacity': 0.9,
      'text-background-shape': 'roundrectangle',
      'text-rotation': 'autorotate',
      'arrow-scale': 1.1,
    },
  },
  {
    selector: 'edge.bridge-edge.is-bridge-hovered',
    style: {
      width: 5,
      'line-color': '#00BC7D',
      'target-arrow-color': '#00BC7D',
      'underlay-opacity': 0.4,
    },
  },
  {
    selector: '.is-active',
    style: {
      'background-color': '#FACC15',
      'border-color': '#EAB308',
      'border-width': 2,
      color: '#1F2937',
      'shadow-blur': 14,
      'shadow-color': '#FACC15',
      'shadow-opacity': 0.24,
    },
  },
  {
    selector: '.is-hovered',
    style: {
      'background-color': 'data(hoverColor)',
      'border-color': 'data(hoverBorderColor)',
      'border-width': 1,
      'shadow-blur': 18,
      'shadow-opacity': 0.28,
      'shadow-offset-y': 0,
      'z-index': 999,
    },
  },
  {
    selector: '.is-highlighted',
    style: {
      'background-color': 'data(highlightColor)',
      'border-color': 'data(highlightBorderColor)',
      'border-width': 1,
      opacity: 1,
    },
  },
  {
    selector: '.is-liked',
    style: {
      'background-color': '#34D399',
      'border-color': '#059669',
      'border-width': 2,
      color: '#052E16',
      'shadow-blur': 16,
      'shadow-color': '#34D399',
      'shadow-opacity': 0.28,
    },
  },
  {
    selector: '.is-disliked',
    style: {
      'background-color': '#FCA5A5',
      'border-color': '#DC2626',
      'border-width': 2,
      color: '#450A0A',
      opacity: 1,
      'shadow-blur': 16,
      'shadow-color': '#F87171',
      'shadow-opacity': 0.24,
    },
  },
  {
    selector: '.is-focused-search',
    style: {
      'background-color': '#FDE047',
      'border-color': '#F59E0B',
      'border-width': 2,
      color: '#1F2937',
    },
  },
  {
    selector: '.is-dimmed',
    style: {
      opacity: 0.16,
    },
  },
  {
    selector: '.is-hidden',
    style: {
      opacity: 0.06,
    },
  },
  {
    selector: '.is-edge-visible',
    style: {
      opacity: 0.94,
      width: 2.8,
      'line-color': '#00BC7D',
      'target-arrow-color': '#00BC7D',
    },
  },
] as StylesheetJson
